openshift/cluster-api-provider-baremetal

Makefile

This was broken by the last cluster-api update.

Makefile: Fix manifests target.

---

pkg/apis/baremetal/v1alpha1/register.go

The latest beta of controller-runtime 0.2 fixed this breakage by adding
a typedef for Builder pointing to scheme.Builder, however this is not
available in vendored version in the installer. Changing the import
works with all betas of controller-runtime 0.2.
Installer builds are failing and I cannot rebase:
```
+ go build -ldflags ' -X github.com/openshift-metalkube/kni-installer/pkg/version.Raw=unreleased-master-1395-gaf434a07b8c96299aac80b88fe6e403c2a5e62ad-dirty -X github.com/openshift-metalkube/kni-installer/pkg/version.Commit=af434a07b8c96299aac80b88fe6e403c2a5e62ad -s -w' -tags 'libvirt release' -o bin/kni-install ./cmd/kni-install
vendor/github.com/metal3-io/cluster-api-provider-baremetal/pkg/apis/baremetal/v1alpha1/register.go:37:19: undefined: scheme.Builder
```
This is the fix …

Fix import for runtime.Scheme

---

vendor/github.com/metal3-io/baremetal-operator/Makefile
vendor/github.com/metal3-io/baremetal-operator/build/Dockerfile
vendor/github.com/metal3-io/baremetal-operator/cmd/make-bm-worker/main.go
vendor/github.com/metal3-io/baremetal-operator/cmd/make-bm-worker/templates/templates.go
vendor/github.com/metal3-io/baremetal-operator/cmd/make-virt-host/main.go
vendor/github.com/metal3-io/baremetal-operator/cmd/manager/main.go
vendor/github.com/metal3-io/baremetal-operator/deploy/crds/demo-hosts.yaml
vendor/github.com/metal3-io/baremetal-operator/deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
vendor/github.com/metal3-io/baremetal-operator/docs/BaremetalHost_ProvisioningState.dot
vendor/github.com/metal3-io/baremetal-operator/docs/api.md
vendor/github.com/metal3-io/baremetal-operator/docs/dev-setup.md
vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go

Update to the version of the baremetal-operator that completes the work to rename machineRef to consumerRef.

update bmo 20190708

---

pkg/cloud/baremetal/actuators/machine/actuator.go

The code already set the NodeHostname address type.  This patch sets
that same value as the NodeInternalDNS.
I ran into a component (openshift/cluster-machine-approver) that
expected a NodeInternalDNS field to be set on the Machine with the
hostname.

Set NodeInternalDNS address on Machine.

---

Makefile

kustomize was interpreting the path argument
`github.com/openshift/cluster-api/config` as a URL instead of a relative file
path. It was doing something with git to retrieve files from github, put them
in a temporary directory (hence the confusing error message about a directory
in /tmp/), then failing to find what it expected.
fixes #48

fixes broken `make manifests`, which was also breaking `make unit`.

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

This is to ensure a new Machine is created by the MachineSet
controller and that it will contain the latest ProviderSpec.
Signed-off-by: Richard Su rwsu@redhat.com

Delete Machine when BareMetalHost is deleted

---

Gopkg.lock
README.md
cmd/manager/main.go
config/rbac/rbac_role.yaml
pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go
pkg/controller/add_machineset.go
pkg/controller/machineset/machineset_controller.go
pkg/controller/machineset/machineset_controller_test.go
pkg/controller/machineset/mapper.go
pkg/controller/machineset/mapper_test.go

In many clusters, it is desirable for the size of a MachineSet to always equal
the number of matching BareMetalHosts. In such a scenario, the cluster owner
wants all of their hardware to be provisioned and turned into Nodes, and they
want to remove excess Machines in case they remove hosts from their cluster.
This change adds a controller that scales MachineSets to the number of matching
BareMetalHosts. The behavior is opt-in, requiring an annotation on the
MachineSet.

adds auto-scaling for MachineSet based on number of BareMetalHosts

---

cmd/manager/main.go
config/default/manager_auth_proxy_patch.yaml

Add a command-line flag to allow leader election to be enabled when
running in a cluster. This is consistent with how leader election is now
done upstream.

Enable leader election

---

docs/api.md

Originally from ba87bda4de (#74).
Generated with:
```console
$ sed -i "s/‘/'/g;s/’/'/g" docs/api.md
```

docs/api: Fix curly quotes in YAML examples

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go
pkg/manager/wrapper/bmh_mapper.go
pkg/manager/wrapper/bmh_mapper_test.go
pkg/manager/wrapper/node_mapper.go
pkg/manager/wrapper/wrapper.go

The current Machine Remediation code is deleting the node object, together with its annotations and labels.
This is problematic because the labels and annotations may be used to organize nodes and assign workloads.
This PR store the annotations and labels on the machine, and restore them when the node re-registers.
Signed-off-by: Nir <niry@redhat.com>

Restore node's annotations and labels after remediation

---

cmd/manager/main.go
docs/probes.md

- Introducing simple readiness probes for controller-runtime, checking the manager container could respond to HTTP requests.
Depends on openshift/machine-api-operator#602
Close #78

Add liveness/readiness probes

---

pkg/cloud/baremetal/actuators/machine/actuator_test.go

@dhellmann [reported](https://github.com/openshift/cluster-api-provider-baremetal/pull/77#issuecomment-653025242) that unit tests fails locally.
This PR fixes the failing test.

Fix failing unit tests in actuator remediation test

---

pkg/cloud/baremetal/actuators/machine/actuator.go

It seems that k8s doesn't accept finalizer name if it doesn't contain /
See this for more details:
https://github.com/kubernetes/kubernetes/blob/205d5c58296357365bfa834ecabb384c1c1042c3/pkg/apis/core/validation/validation.go#L5515
Also, I got an error after adding trailing / without any value
Fixing https://bugzilla.redhat.com/show_bug.cgi?id=1855049
The error message:
```
020/07/08 18:12:51 Failed to add node finalizer to node worker-0-0, error: Node "worker-0-0" is invalid: metadata.finalizers[0]: Invalid value: "capbm.metal3.io": name is neither a standard finalizer name nor is it fully qualified     
E0708 18:12:51.059738       1 controller.go:275] ocp-edge-cluster-rdu2-0-worker-0-p722p: error updating machine: Node "worker-0-0" is invalid: metadata.finalizers[0]: Invalid value: …
```

Change node finalizer name to match api requirements

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

The cluster autoscaler expects this to be set on both machines and nodes, and typically the cluster-api provider will set the
value in the spec for the machine e.g    
https://github.com/openshift/cluster-api-provider-aws/blob/master/pkg/actuators/machine/reconciler.go#L280
In the baremetal case though there's no "provider" to set the value on the node, so we also update that correspondingly (TODO)
https://bugzilla.redhat.com/show_bug.cgi?id=1852959

Bug 1852959: Add ProviderID

---

go.mod
go.sum
vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
vendor/modules.txt

Pull the metal3 baremetal-operator code from the OpenShift fork
instead of the upstream repository. This keeps us in sync with the BMO
in OpenShift to ensure we don't have an incompatibility by pulling
upstream changes too quickly.

update baremetal-operator module source location

---

cmd/manager/main.go

Fix `leader-election` cli option for machine controller, allowing to eliminate edge cases when multiple controllers could be running. Allows integration with MAO PR: openshift/machine-api-operator#571

Change leader election flags for MAO support

---

cmd/manager/main.go
config/default/manager_prometheus_metrics_patch.yaml

This change ensures compatibility with the `ServiceMonitor` resource
introduced in openshift/machine-api-operator#609
Close #75

Fix metrics

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

We were not removing the host annotation from the machine, which made
it appear to always be deleting. This change reorganizes the Delete()
function in the actuator to ensure that all of the progressive steps
of deprovisioning the host and then removing both links between the
machine and host are handled.
https://bugzilla.redhat.com/show_bug.cgi?id=1855823

ensure delete removes the link between machine and host

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

When a Machine is deleted, any host it was using should have all
associations with Machines removed. We were removing the explicit
links to the machine, but not the finalizer that the machine
controller added. This change removes the finalizer so that hosts that
are no longer being consumed by a machine can be deleted.
https://bugzilla.redhat.com/show_bug.cgi?id=1837505

remove machine finalizer from host when deleting machine

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

If a host was externally provisioned and not linked directly to the machine
for which we're looking for a host, we want to ignore it to avoid
overwriting whatever image is on the host now.
Includes a bit of code cleanup.
Fixes #91

ignore externally provisioned hosts when looking for candidates

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

This PR depends on #93 and should be rebased after it merges
/hold

Bug 1862875: remove machine finalizer from host when deleting machine

---

Makefile

The existing unit target is useful for running tests locally by hand
because it ensures the manifests are up to date. This new target runs
only the tests, without building the manifests, and can be used in a
CI job where kustomize is not available to (a) run the tests and (b)
ensure that the output of kustomize is checked in to the repo.
See https://github.com/openshift/release/pull/11458
/assign @zaneb

Bug 1874618: add a make target to run only the unit tests

---

hack/ci-test.sh
hack/fetch_ext_bins.sh

These scripts are copied from the MAO and CBO repositories.
Needed for https://github.com/openshift/release/pull/11458

Bug 1874618: add hack scripts to install dependencies for unit tests

---

go.mod
pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

Fix some unit test failures that slipped past because we are not running
the unit tests in CI.

Bug 1874618: fix unit tests so we can add a CI job

---

pkg/cloud/baremetal/actuators/machine/actuator.go

We were in the middle of changing StateReady to StateAvailable. We need
to be able to handle both.

Bug 1879284: Handle StateAvailable

---

go.mod
go.sum
vendor/github.com/openshift/machine-api-operator/Dockerfile.rhel
vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
vendor/modules.txt

This change is being proposed to pick up the recent log message changes as proposed in https://github.com/openshift/machine-api-operator/pull/681

Bug 1878880: re-vendor machine-api-operator at e0db6b65

---

pkg/cloud/baremetal/actuators/machine/actuator.go

Ensure the Node finalizer is removed even if the Host used by the
Machine has already been deleted by some external means.

Bug 1886028: Remove Node finalizer first on delete

---

pkg/cloud/baremetal/actuators/machine/actuator.go

The only time it is safe to add a finalizer to a Node is when there is a MachineHealthCheck maintaining the Machine. When a Machine is in the `failed` phase, the actuator is not called again until the Machine is deleted, so the actuator would be unable to remove the finalizer and the Node would be immortal until the Machine is deleted. (A MachineHealthCheck will ensure that any Machine in the failed phase will be deleted promptly.) Although we currently do not put baremetal Machines into the `failed` phase, this is planned for the near future in #113.
At the time the finalizer was implemented (in #67) it was thought potentially valuable to always capture the Node's metadata before it was deleted for any cause, so that it could always be restored. But in practice we only restore the data …

Don't add a finalizer to the Node

---

README.md

To utilize power-cycle remediation, an admin should add that annotation to the MHC CR, and not the MHC CRD

Fix typo in readme - annotation should exist on CR, not CRD

---

pkg/cloud/baremetal/actuators/machine/actuator.go

This will enable the assisisted installer host to be linked

Allow actuator.Exists() to find a host in the unmanaged state

---

OWNERS

As the team lead for the team that manages this repo, Stephen should be
able to merge patches.

add stbenjam to owners file

---

Dockerfile.rhel

Updating baremetal-machine-controller builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/baremetal-machine-controller.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating baremetal-machine-controller builder & base images to be consistent with ART

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

This sets the Machine instance-state to the bmh provisioningState.
It is not strictly required, but nice as it displays in the output of "oc get -n openshift-machine-api machine -o wide"
see: https://github.com/openshift/machine-api-operator/blob/master/pkg/apis/machine/v1beta1/machine_types.go#L53
Examples of other platforms doing this:
- https://github.com/openshift/cluster-api-provider-kubevirt/blob/master/pkg/machinescope/machine_scope.go#L372-L384
- https://github.com/openshift/cluster-api-provider-gcp/blob/master/pkg/cloud/gcp/actuators/machine/reconciler.go#L263

Bug 1857008: Set the machine instance state annotation

---

pkg/cloud/baremetal/actuators/machine/actuator.go

This prevents a race condition by allowing the cache to get updated with
the new annotation.
cc @zaneb

Bug 2061833: Delay after ensuring annotation

---

pkg/cloud/baremetal/actuators/machine/actuator.go

It's important to know to be able to trace what is updating BMH's.
In all other places, we do log when there is a diff, but not for hosts.

NO-ISSUE: Log when applying updates to BareMetalHost
